core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('products.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.contrib.auth.models import User
from django.db import models
from .helpers import SaveMediaFiles


class PriceType(models.TextChoices):
    EURO = 'EURO', 'EURO'
    DOLLAR = '$', '$'
    SUM = 'SO`M', 'SO`M'


class Product(models.Model):
    image = models.ImageField(upload_to=SaveMediaFiles.product_image)
    name = models.CharField(max_length=25, null=True)
    slug = models.SlugField(unique=True, verbose_name='Slug', max_length=100)
    price = models.IntegerField()
    count = models.IntegerField()
    price_type = models.CharField(max_length=4, choices=PriceType.choices)
    description = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('id',)
        db_table = 'products'
        indexes = [
            models.Index(fields=['id'])
        ]

    def __str__(self):
        return self.name


class Comment(models.Model):
    image = models.ImageField(upload_to=SaveMediaFiles.clientcomment_image)
    name = models.CharField(max_length=150)
    slug = models.SlugField(unique=True, verbose_name='Slug', max_length=100)
    comment = models.TextField()
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('id',)
        db_table = 'comments'
        indexes = [
            models.Index(fields=['id'])
        ]

    def __str__(self):
        return self.name


class Team(models.Model):
    image = models.ImageField(upload_to=SaveMediaFiles.clientcomment_image)
    name = models.CharField(max_length=80)
    slug = models.SlugField(unique=True, verbose_name='Slug', max_length=100)
    staff_type = models.CharField(max_length=150)
    title = models.CharField(max_length=80)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('id',)
        db_table = 'teams'
        indexes = [
            models.Index(fields=['id'])
        ]

    def __str__(self):
        return self.name


class Blog(models.Model):
    image = models.ImageField(upload_to=SaveMediaFiles.blog_image)
    name = models.CharField(max_length=150)
    slug = models.SlugField(unique=True, verbose_name='Slug', max_length=100)
    who = models.CharField(max_length=150)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('id',)
        db_table = 'blogs'
        indexes = [
            models.Index(fields=['id'])
        ]

    def __str__(self):
        return self.name


class Testimonials(models.Model):
    content = models.TextField()
    slug = models.SlugField(unique=True, verbose_name='Slug', max_length=100)
    image = models.ImageField(upload_to=SaveMediaFiles.testimonial)
    client_name = models.CharField(max_length=100)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.client_name


class ProductsUsers(models.Model):
    full_name = models.CharField(max_length=50, null=True, blank=False)
    username = models.CharField(max_length=30, null=True, unique=True)
    telegram_id = models.PositiveBigIntegerField(unique=True)
    create_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'products_users'


class ProductsProducts(models.Model):
    name = models.CharField(max_length=40)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    description = models.TextField(null=True)
    category_code = models.CharField(max_length=20)
    category_name = models.CharField(max_length=30)
    subcategory_code = models.CharField(max_length=20)
    subcategory_name = models.CharField(max_length=20)

    def __str__(self):
        return f"{self.name}"

    class Meta:
        db_table = 'products_product'

templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

		

		<!-- Start Why Choose Us Section -->
		<div class="why-choose-section">
			<div class="container">
				<div class="row justify-content-between align-items-center">
					<div class="col-lg-6">
						<h2 class="section-title">Why Choose Us</h2>
						<p>Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate velit imperdiet dolor tempor tristique.</p>

						<div class="row my-5">
							<div class="col-6 col-md-6">
								<div class="feature">
									<div class="icon">
										<img src="../static/main/images/truck.svg" alt="Image" class="imf-fluid">
									</div>
									<h3>Fast &amp; Free Shipping</h3>
									<p>Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate.</p>
								</div>
							</div>

							<div class="col-6 col-md-6">
								<div class="feature">
									<div class="icon">
										<img src="../static/main/images/bag.svg" alt="Image" class="imf-fluid">
									</div>
									<h3>Easy to Shop</h3>
									<p>Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate.</p>
								</div>
							</div>

							<div class="col-6 col-md-6">
								<div class="feature">
									<div class="icon">
										<img src="../static/main/images/support.svg" alt="Image" class="imf-fluid">
									</div>
									<h3>24/7 Support</h3>
									<p>Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate.</p>
								</div>
							</div>

							<div class="col-6 col-md-6">
								<div class="feature">
									<div class="icon">
										<img src="../static/main/images/return.svg" alt="Image" class="imf-fluid">
									</div>
									<h3>Hassle Free Returns</h3>
									<p>Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate.</p>
								</div>
							</div>

						</div>
					</div>

					<div class="col-lg-5">
						<div class="img-wrap">
							<img src="../static/main/images/why-choose-us-img.jpg" alt="Image" class="img-fluid">
						</div>
					</div>

				</div>
			</div>
		</div>
		<!-- End Why Choose Us Section -->

		<!-- Start Team Section -->
		<div class="untree_co-section">
			<div class="container">

				<div class="row mb-5">
					<div class="col-lg-5 mx-auto text-center">
						<h2 class="section-title">Our Team</h2>
					</div>
				</div>
				<div class="row">
				{% for team in teams %}
					<!-- Start Column 1 -->
					<div class="col-12 col-md-6 col-lg-3 mb-5 mb-md-0">
						<img src="{{ team.image.url }}" class="img-fluid mb-5">
						<h3 class><a href="#"> {{ team.name }}</a></h3>
            			<span class="d-block position mb-4">{{ team.name }}</span>
						<p>{{team.title}}</p>
					</div>

				{%endfor%}	<!-- End Column 1 -->


					

				</div>
			</div>
		</div>
		<!-- End Team Section -->

		

		<!-- Start Testimonial Slider -->
		<div class="testimonial-section">
			<div class="container">
				<div class="row">
					<div class="col-lg-7 mx-auto text-center">
						<h2 class="section-title">Testimonials</h2>
					</div>
				</div>

				<div class="row justify-content-center">
					<div class="col-lg-12">
						<div class="testimonial-slider-wrap text-center">
							<div id="testimonial-nav">
								<span class="prev" data-controls="prev"><span class="fa fa-chevron-left"></span></span>
								<span class="next" data-controls="next"><span class="fa fa-chevron-right"></span></span>
							</div>
							<div class="testimonial-slider">
							{%for comment in comments%}
								<div class="item">
									<div class="row justify-content-center">
										<div class="col-lg-8 mx-auto">
											<div class="testimonial-block text-center">
												<blockquote class="mb-5">
													<p>&ldquo; {{comment.comment}} &rdquo;</p>
												</blockquote>
												<div class="author-info">
													<div class="author-pic">
														<img src="{{comment.image.url}}" alt="{{comment.name}}" class="img-fluid">
													</div>
													<h3 class="font-weight-bold">{{comment.name}}</h3>
													<span class="position d-block mb-3">{{comment.date}}</span>
												</div>
											</div>
										</div>
									</div>
								</div>
							{%endfor%}
								<!-- END item -->
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- End Testimonial Slider -->

		

{% endblock %}

templates/base.html
{%load static%}
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="author" content="Untree.co">
  <link rel="shortcut icon" href="favicon.png">

  <meta name="description" content="" />
  <meta name="keywords" content="bootstrap, bootstrap4" />

		<!-- Bootstrap CSS -->
		<link href="../static/main/css/bootstrap.min.css" rel="stylesheet">
		<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
		<link href="../static/main/css/tiny-slider.css" rel="stylesheet">
		<link href="../static/main/css/style.css" rel="stylesheet">
		<title>Furni by Hojiakbar </title>

	<script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>

	</head>

	<body>

		<!-- Start Header/Navigation -->
		<nav class="custom-navbar navbar navbar navbar-expand-md navbar-dark bg-dark" arial-label="Furni navigation bar">
			{% csrf_token %}

			<div class="container">
				<a class="navbar-brand" href="{%url 'landing'%}">Furni<span>.</span></a>

				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsFurni" aria-controls="navbarsFurni" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>

				<div class="collapse navbar-collapse" id="navbarsFurni">
					<ul class="custom-navbar-nav navbar-nav ms-auto mb-2 mb-md-0">
						<form method="get" action="{% url 'shop' %}" class="form-inline my-2 my-lg-0">
    						<div class="input-group">
        						<input type="text" class="form-control" placeholder="Search for products" name="search">
        						<div class="input-group-append">
            						<button class="btn btn-outline-secondary" type="submit">Search</button>
								</div>
    						</div>
						</form>

						<li class="nav-item">
							{% if request.user.is_authenticated %}
							<a class="nav-link " href="{%url 'landing'%}">Home</a>
							{% else %}
							<a class="nav-link " href="{%url 'register'%}">Home</a>
							{% endif %}
						</li>
						<li class="">
							{% if request.user.is_authenticated %}
							<a class="nav-link" href="{%url 'shop'%}">Shop</a>
							{% else %}
							<a class="nav-link" href="{%url 'register'%}">Shop</a>
							{% endif %}
						</li>
						<li>
							{% if request.user.is_authenticated %}
							<a class="nav-link" href="{%url 'about'%}">About us</a>
							{% else %}
							<a class="nav-link" href="{%url 'register'%}">About us</a>
							{% endif %}
						</li>
						<li>
							{% if request.user.is_authenticated %}
							<a class="nav-link" href="{%url 'services'%}">Services</a>
							{% else %}
							<a class="nav-link" href="{%url 'register'%}">Services</a>
							{% endif %}
						</li>
						<li>
							{% if request.user.is_authenticated %}
							<a class="nav-link" href="{%url 'blog'%}">Blog</a>
							{% else %}
							<a class="nav-link" href="{%url 'register'%}">Blog</a>
							{% endif %}
						</li>
						<li>
							{% if request.user.is_authenticated %}
							<a class="nav-link" href="{%url 'contact'%}">Contact us</a>
							{% else %}
							<a class="nav-link" href="{%url 'register'%}">Contact us</a>
							{% endif %}
						</li>
					</ul>

					<ul class="custom-navbar-cta navbar-nav mb-2 mb-md-0 ms-5">
    					<li class="nav-item dropdown">
        					<a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            					<img src="../static/main/images/user.svg" alt="UserProfile">
        					</a>
        			<ul class="dropdown-menu" aria-labelledby="userDropdown">
			{% if request.user.is_authenticated %}
			<li><a class="dropdown-item" href="{%url 'profile'%}">Profile <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 48 48"><g fill="black"><path d="M32 20a8 8 0 1 1-16 0a8 8 0 0 1 16 0"/><path fill-rule="evenodd" d="M23.184 43.984C12.517 43.556 4 34.772 4 24C4 12.954 12.954 4 24 4s20 8.954 20 20s-8.954 20-20 20h-.274q-.272 0-.542-.016M11.166 36.62a3.028 3.028 0 0 1 2.523-4.005c7.796-.863 12.874-.785 20.632.018a2.99 2.99 0 0 1 2.498 4.002A17.94 17.94 0 0 0 42 24c0-9.941-8.059-18-18-18S6 14.059 6 24c0 4.916 1.971 9.373 5.166 12.621" clip-rule="evenodd"/></g></svg></a></li>
            <li><a class="dropdown-item" href="{%url 'register'%}">Logout <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 8 8"><path fill="black" d="M3 0v1h4v5H3v1h5V0zM2 2L0 3.5L2 5V4h4V3H2z"/></svg></a></li>
			{%else%}
			<li><a class="dropdown-item" href="{%url 'login'%}">Login <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24"><path fill="black" d="M11 7L9.6 8.4l2.6 2.6H2v2h10.2l-2.6 2.6L11 17l5-5zm9 12h-8v2h8c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2h-8v2h8z"/></svg></a></li><li><a class="dropdown-item" href="{%url 'register'%}">Register <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 16 16"><path fill="black" fill-rule="evenodd" d="M1.5 2h13l.5.5v10l-.5.5h-13l-.5-.5v-10zM2 3v9h12V3zm2 2h8v1H4zm6 2H4v1h6zM4 9h4v1H4z" clip-rule="evenodd"/></svg></a></li>
			{% endif %}
        </ul>
    </li>
    <li class="nav-item">
		{% if user.is_authenticated %}
        <a class="nav-link" href="{% url 'cart' %}">
            <img src="../static/main/images/cart.svg" alt="Cart">
        </a>
		{% else %}
		<a class="nav-link" href="{% url 'register' %}">
            <img src="../static/main/images/cart.svg" alt="Cart">
        </a>
		{% endif %}
    </li>
</ul>

				</div>
			</div>
		</nav>
		<!-- End Header/Navigation -->





	{% block content %}
	{% endblock %}









		<!-- Start Footer Section -->
		<footer class="footer-section">
			<div class="container relative">

				<div class="sofa-img">
					<img src="../static/main/images/sofa.png" alt="Image" class="img-fluid">
				</div>

				<div class="row">
					<div class="col-lg-8">
						<div class="subscription-form">
							<h3 class="d-flex align-items-center"><span class="me-1"><img src="../static/main/images/envelope-outline.svg" alt="Image" class="img-fluid"></span><span>Subscribe to Newsletter</span></h3>

							<form action="#" class="row g-3">
								<div class="col-auto">
									<input type="text" class="form-control" placeholder="Enter your name">
								</div>
								<div class="col-auto">
									<input type="email" class="form-control" placeholder="Enter your email">
								</div>
								<div class="col-auto">
									<button class="btn btn-primary">
										<span class="fa fa-paper-plane"></span>
									</button>
								</div>
							</form>

						</div>
					</div>
				</div>

				<div class="row g-5 mb-5">
					<div class="col-lg-4">
						<div class="mb-4 footer-logo-wrap"><a href="#" class="footer-logo">Furni<span>.</span></a></div>
						<p class="mb-4">Donec facilisis quam ut purus rutrum lobortis. Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate velit imperdiet dolor tempor tristique. Pellentesque habitant</p>

						<ul class="list-unstyled custom-social">
							<li><a href="#"><span class="fa fa-brands fa-facebook-f"></span></a></li>
							<li><a href="#"><span class="fa fa-brands fa-twitter"></span></a></li>
							<li><a href="#"><span class="fa fa-brands fa-instagram"></span></a></li>
							<li><a href="#"><span class="fa fa-brands fa-linkedin"></span></a></li>
						</ul>
					</div>

					<div class="col-lg-8">
						<div class="row links-wrap">
							<div class="col-6 col-sm-6 col-md-3">
								<ul class="list-unstyled">
									<li><a href="{% url 'about' %}">About us</a></li>
									<li><a href="{% url 'services' %}">Services</a></li>
									<li><a href="{% url 'blog' %}">Blog</a></li>
									<li><a href="{% url 'contact' %}">Contact us</a></li>
								</ul>
							</div>

							<div class="col-6 col-sm-6 col-md-3">
								<ul class="list-unstyled">
									<li><a href="{% url 'contact' %}">Support</a></li>
									<li><a href="#">Knowledge base</a></li>
									<li><a href="#">Live chat</a></li>
								</ul>
							</div>

							<div class="col-6 col-sm-6 col-md-3">
								<ul class="list-unstyled">
									<li><a href="#">Jobs</a></li>
									<li><a href="#">Our team</a></li>
									<li><a href="#">Leadership</a></li>
									<li><a href="#">Privacy Policy</a></li>
								</ul>
							</div>

							<div class="col-6 col-sm-6 col-md-3">
								<ul class="list-unstyled">
									<li><a href="#">Nordic Chair</a></li>
									<li><a href="#">Kruzo Aero</a></li>
									<li><a href="#">Ergonomic Chair</a></li>
								</ul>
							</div>
						</div>
					</div>

				</div>

				<div class="border-top copyright">
					<div class="row pt-4">
						<div class="col-lg-6">
							<p class="mb-2 text-center text-lg-start">Copyright &copy;<script>document.write(new Date().getFullYear());</script>. All Rights Reserved. &mdash; Designed with love by <a href="https://untree.co">Untree.co</a> <!-- License information: https://untree.co/license/ -->
            </p>
						</div>

						<div class="col-lg-6 text-center text-lg-end">
							<ul class="list-unstyled d-inline-flex ms-auto">
								<li class="me-4"><a href="#">Terms &amp; Conditions</a></li>
								<li><a href="#">Privacy Policy</a></li>
							</ul>
						</div>

					</div>
				</div>

			</div>
		</footer>
		<!-- End Footer Section -->


		<script src="../static/main/js/bootstrap.bundle.min.js"></script>
		<script src="../static/main/js/tiny-slider.js"></script>
		<script src="../static/main/js/custom.js"></script>
	</body>

</html>

templates/blog.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

		

		<!-- Start Blog Section -->
		<div class="blog-section">
			<div class="container">
				
				<div class="row">


				{%for blog in blogs%}
					<div class="col-12 col-sm-6 col-md-4 mb-5">
						<div class="post-entry">
							<a href="" class="post-thumbnail"><img src="{{blog.image.url}}" alt="Image" width="300px" height="300px"></a>
							<div class="post-content-entry">
								<h3><a href="#">{{blog.name}}</a></h3>
								<div class="meta">
									<span>by <a href="#">{{blog.who}}</a></span> <span>on <a href="#">{{blog.date}}</a></span>
								</div>
							</div>
						</div>
					</div>
				{%endfor%}


				</div>
			</div>
		</div>
		<!-- End Blog Section -->	

		

		<!-- Start Testimonial Slider -->
		<div class="testimonial-section">
			<div class="container">
				<div class="row">
					<div class="col-lg-7 mx-auto text-center">
						<h2 class="section-title">Testimonials</h2>
					</div>
				</div>

				<div class="row justify-content-center">
					<div class="col-lg-12">
						<div class="testimonial-slider-wrap text-center">

							<div id="testimonial-nav">
								<span class="prev" data-controls="prev"><span class="fa fa-chevron-left"></span></span>
								<span class="next" data-controls="next"><span class="fa fa-chevron-right"></span></span>
							</div>

							<div class="testimonial-slider">


							{%for comment in comments%}
								<div class="item">
									<div class="row justify-content-center">
										<div class="col-lg-8 mx-auto">

											<div class="testimonial-block text-center">
												<blockquote class="mb-5">
													<p>&ldquo; {{comment.comment}} &rdquo;</p>
												</blockquote>

												<div class="author-info">
													<div class="author-pic">
														<img src="{{comment.image.url}}" alt="{{comment.name}}" class="img-fluid">
													</div>
													<h3 class="font-weight-bold">{{comment.name}}</h3>
													<span class="position d-block mb-3">{{comment.date}}</span>
												</div>
											</div>

										</div>
									</div>
								</div>
							{%endfor%}
								<!-- END item -->

							</div>

						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- End Testimonial Slider -->

{% endblock %}

templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

		<div class="untree_co-section before-footer-section">
            <div class="container">
              <div class="row mb-5">
                <form class="col-md-12" method="post">
                  <div class="site-blocks-table">
                    <table class="table">
                      <thead>
                        <tr>
                          <th class="product-thumbnail">Image</th>
                          <th class="product-name">Product</th>
                          <th class="product-price">Price</th>
                          <th class="product-quantity">Quantity</th>
                          <th class="product-total">Total</th>
                          <th class="product-remove">Remove</th>
                        </tr>
                      </thead>
                      <tbody>
                      {% for product in products %}
                        <tr>
                          <td class="product-thumbnail">
                            <img src="{{product.image.url}}" alt="Image" class="img-fluid">

                          </td>
                          <td class="product-name">
                            <h2 class="h5 text-black">{{ product.name }}</h2>
                          </td>
                          <td>{{ product.price }}{{ product.price_type }}</td>
                          <td>
                            <div class="input-group mb-3 d-flex align-items-center quantity-container" style="max-width: 120px;">
                              <div class="input-group-prepend">
                                <button class="btn btn-outline-black decrease" type="button">&minus;</button>
                              </div>
                              <input type="text" class="form-control text-center quantity-amount" value="1" placeholder="" aria-label="Example text with button addon" aria-describedby="button-addon1">
                              <div class="input-group-append">
                                <button class="btn btn-outline-black increase" type="button">&plus;</button>
                              </div>
                            </div>
                          </td>
                          <td>{{ product.price }}{{ product.price_type }}</td>
                          <td><a href="#" class="btn btn-black btn-sm">X</a></td>
                        </tr>
                      <tr>
                        </tr>
                      {% endfor %}
                      </tbody>
                    </table>
                  </div>
                </form>
              </div>
        
              <div class="row">
                <div class="col-md-6">
                  <div class="row mb-5">
                    <div class="col-md-6 mb-3 mb-md-0">
                      <button class="btn btn-black btn-sm btn-block">Update Cart</button>
                    </div>
                    <div class="col-md-6">
                      <button class="btn btn-outline-black btn-sm btn-block">Continue Shopping</button>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-md-12">
                      <label class="text-black h4" for="coupon">Coupon</label>
                      <p>Enter your coupon code if you have one.</p>
                    </div>
                    <div class="col-md-8 mb-3 mb-md-0">
                      <input type="text" class="form-control py-3" id="coupon" placeholder="Coupon Code">
                    </div>
                    <div class="col-md-4">
                      <button class="btn btn-black">Apply Coupon</button>
                    </div>
                  </div>
                </div>
                <div class="col-md-6 pl-5">
                  <div class="row justify-content-end">
                    <div class="col-md-7">
                      <div class="row">
                        <div class="col-md-12 text-right border-bottom mb-5">
                          <h3 class="text-black h4 text-uppercase">Cart Totals</h3>
                        </div>
                      </div>
                      <div class="row mb-3">
                        <div class="col-md-6">
                          <span class="text-black">Subtotal</span>
                        </div>
                        <div class="col-md-6 text-right">
                          <strong class="text-black">${{ total_price }}</strong>
                        </div>
                      </div>
                      <div class="row mb-5">
                        <div class="col-md-6">
                          <span class="text-black">Total</span>
                        </div>
                        <div class="col-md-6 text-right">
                          <strong class="text-black">$230.00</strong>
                        </div>
                      </div>
        
                      <div class="row">
                        <div class="col-md-12">
                          <button class="btn btn-black btn-lg py-3 btn-block" onclick="window.location='checkout.html'">Proceed To Checkout</button>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
		

{% endblock %}

templates/product_update.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <h1 class="mt-4">Update Product</h1>
    <form method="post" enctype="multipart/form-data" class="mt-4">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_name">Name</label>
            <input type="text" class="form" id="id_name" name="name" value="{{ form.name.value }}" placeholder="Enter product name">
        </div>
        <div class="form-group mt-3">
            <label for="id_price">Price</label>
            <input type="number" class="form" id="id_price" name="price" value="{{ form.price.value }}" placeholder="Enter product price">
        </div>
        <div class="form-group mt-3">
            <label for="id_image">Image</label>
            <input type="file" class="form-control-file" id="id_image" name="image">
            {% if form.image.value %}
                <div class="mt-3">
                    <img src="{{ form.image.value.url }}" class="img-thumbnail" alt="Current product image" width="150">
                </div>
            {% endif %}
        </div>
        <div class="mt-4 d-flex justify-content-between">
            <button type="submit" class="btn btn-success">Update</button>
            <a href="{% url 'shop' %}" class="btn btn-danger">Cancel</a>
        </div>
    </form>
</div>
{% endblock %}

templates/shop.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="untree_co-section product-section before-footer-section">
    <div class="container">
        <div class="row">
            {% for product in products %}
                <!-- Start Column 1 -->
                <div class="col-12 col-md-4 col-lg-3 mb-5">
                    <a class="product-item" href="{% url 'detail' product.slug %}">
                        <img src="{{ product.image.url }}" class="product-thumbnail" width="250px" height="250px" alt="Product Image">
                        <h3 class="product-title">{{ product.name }}</h3>
                        <strong class="product-price">{{ product.price_type }} {{ product.price }}</strong>
                    </a>
                    {% if user.is_staff %}
                <div class="btn-container">
                    <a class="btn btn-primary" href="{% url 'product-update' product.slug %}">Update</a>
                    <a class="btn btn-danger" href="{% url 'product-delete' product.slug %}">Delete</a>
                </div>
            {% endif %}
                </div>
                <!-- End Column 1 -->
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}